version: "3.7"

services:
  app:
    build: .
    container_name: node
    command: yarn dev
    ports:
        - 3333:3333
    environment:
        - DB_HOST=database
    volumes:
        - .:/usr/app

  database:
    image: mongo
    container_name: mongo
    ports:
        - 27017:27017
    volumes:
        - db_data:/data/db
        # - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
        # - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
        # - ./.docker/mongodb/data/db/:/data/db/
        # - ./.docker/mongodb/data/log/:/var/log/mongodb/
